# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20160124_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchfield',
            name='category',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='item',
            new_name='from_user_item',
        ),
        migrations.AddField(
            model_name='notification',
            name='parent_notification',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.Notification'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='notification',
            name='to_user_item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='to_user_item', to='main.Item'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SearchField',
        ),
    ]
